<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>AtsExCsTemplate.MapPlugin</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="oldlife.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BveEx.CoreExtensions" Version="2.0.0" />
    <PackageReference Include="BveEx.Diagnostics" Version="2.0.0" />
    <PackageReference Include="BveEx.PluginHost" Version="2.0.0" />
    <PackageReference Include="Lib.Harmony" Version="2.3.3" />
    <PackageReference Include="ObjectiveHarmonyPatch" Version="1.1.0" />
    <PackageReference Include="SlimDX" Version="4.0.13.44" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AtsEx.PluginHost">
      <HintPath>..\..\..\..\..\..\Public\Documents\AtsEx\1.0\AtsEx.PluginHost.dll</HintPath>
    </Reference>
    <Reference Include="Automatic9045.AtsEx.StructureReuser">
      <HintPath>..\..\..\..\ビルド置き場\MetroDrive-Unity\Apps\BveTs\BveTs6\Input Devices\AtsEx\1.0\Extensions\Automatic9045.AtsEx.StructureReuser.dll</HintPath>
    </Reference>
    <Reference Include="BveTypes">
      <HintPath>..\BveTypes.dll</HintPath>
    </Reference>
    <Reference Include="Mackoy.IInputDevice">
      <HintPath>..\..\..\..\..\..\..\Program Files (x86)\mackoy\BveTs5\Mackoy.IInputDevice.DLL</HintPath>
    </Reference>
  </ItemGroup>

</Project>